import Vue from 'vue'
import { Main,DropdownItem,Dropdown,Header,Aside,Button,Form,FormItem,Input,Row,Col,Tree,Table,tableColumn,Loading,Icon,Breadcrumb,BreadcrumbItem,DropdownMenu,Container } from 'element-ui'

Vue.use(Button)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Row)
Vue.use(Col)
Vue.use(Tree)
Vue.use(Table)
Vue.use(tableColumn)
Vue.use(tableColumn)
Vue.use(Loading)
Vue.use(Icon)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(DropdownMenu)
Vue.use(Container)
Vue.use(Aside)
Vue.use(Header)
Vue.use(Dropdown)
Vue.use(DropdownItem)
Vue.use(Main)
